// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMsCJFL-31FKefapjOAxkgutHmOWLzlEU',
    appId: '1:910419735016:web:4f0dca23d18dd18aae745d',
    messagingSenderId: '910419735016',
    projectId: 'tontine-pro-97133',
    authDomain: 'tontine-pro-97133.firebaseapp.com',
    storageBucket: 'tontine-pro-97133.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVJQOppxO90PioE9AHB_VgxfH6rnFYe7Q',
    appId: '1:910419735016:android:bdd2d189d0457367ae745d',
    messagingSenderId: '910419735016',
    projectId: 'tontine-pro-97133',
    storageBucket: 'tontine-pro-97133.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9s3QHluP-kY8I-AaACR61wIJp-M447Fw',
    appId: '1:910419735016:ios:95c4a3303bd6d173ae745d',
    messagingSenderId: '910419735016',
    projectId: 'tontine-pro-97133',
    storageBucket: 'tontine-pro-97133.firebasestorage.app',
    iosBundleId: 'com.example.tontineApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9s3QHluP-kY8I-AaACR61wIJp-M447Fw',
    appId: '1:910419735016:ios:95c4a3303bd6d173ae745d',
    messagingSenderId: '910419735016',
    projectId: 'tontine-pro-97133',
    storageBucket: 'tontine-pro-97133.firebasestorage.app',
    iosBundleId: 'com.example.tontineApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMsCJFL-31FKefapjOAxkgutHmOWLzlEU',
    appId: '1:910419735016:web:cfff20fa1c5d77deae745d',
    messagingSenderId: '910419735016',
    projectId: 'tontine-pro-97133',
    authDomain: 'tontine-pro-97133.firebaseapp.com',
    storageBucket: 'tontine-pro-97133.firebasestorage.app',
  );
}
