import 'package:flutter/material.dart';
import 'package:get/get.dart';
import '../../../../core/theme/app_theme.dart';
import '../../../controllers/wave_controller.dart';
import '../../../../data/models/wave_model.dart'; // Ensure correct import for WaveModel and WaveStatus

class CreateWaveDialog extends StatefulWidget {
  final WaveModel? wave;

  const CreateWaveDialog({super.key, this.wave});

  @override
  State<CreateWaveDialog> createState() => _CreateWaveDialogState();
}

class _CreateWaveDialogState extends State<CreateWaveDialog> {
  final _formKey = GlobalKey<FormState>();
  late TextEditingController _nameController;
  late WaveStatus _status;

  @override
  void initState() {
    super.initState();
    _nameController = TextEditingController(text: widget.wave?.name ?? '');
    _status = widget.wave?.status ?? WaveStatus.draft;
  }

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    final waveController = Get.put(WaveController());
    final isEditing = widget.wave != null;

    return AlertDialog(
      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(24)),
      title: Text(
        isEditing ? 'Modifier la Vague' : 'Nouvelle Vague',
        style: const TextStyle(
          fontSize: 24,
          fontWeight: FontWeight.bold,
          color: AppTheme.deepBlue,
        ),
      ),
      content: SingleChildScrollView(
        child: Form(
          key: _formKey,
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              TextFormField(
                controller: _nameController,
                decoration: InputDecoration(
                  labelText: 'Nom de la vague',
                  hintText: 'ex: Décembre 2025',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  filled: true,
                  fillColor: AppTheme.warmCream.withOpacity(0.5),
                ),
                validator: (value) {
                  if (value == null || value.isEmpty) {
                    return 'Veuillez entrer un nom';
                  }
                  return null;
                },
              ),
              const SizedBox(height: 16),
              DropdownButtonFormField<WaveStatus>(
                value: _status,
                decoration: InputDecoration(
                  labelText: 'Statut',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(12),
                  ),
                  filled: true,
                  fillColor: AppTheme.warmCream.withOpacity(0.5),
                ),
                items: WaveStatus.values.map((status) {
                  return DropdownMenuItem(
                    value: status,
                    child: Text(_getStatusLabel(status)),
                  );
                }).toList(),
                onChanged: (value) {
                  if (value != null) {
                    setState(() {
                      _status = value;
                    });
                  }
                },
              ),
            ],
          ),
        ),
      ),
      actions: [
        TextButton(
          onPressed: () => Get.back(),
          child: const Text('Annuler'),
        ),
        ElevatedButton(
          onPressed: () async {
            if (_formKey.currentState!.validate()) {
              if (isEditing) {
                final updatedWave = WaveModel(
                  id: widget.wave!.id,
                  name: _nameController.text,
                  status: _status,
                  createdAt: widget.wave!.createdAt,
                );
                await waveController.updateWave(updatedWave);
              } else {
                final newWave = WaveModel(
                  id: '', // Generated by repo
                  name: _nameController.text,
                  status: _status,
                  createdAt: DateTime.now(),
                );
                await waveController.createWave(newWave);
              }
            }
          },
          style: ElevatedButton.styleFrom(
            backgroundColor: AppTheme.deepBlue,
            foregroundColor: Colors.white,
            shape: RoundedRectangleBorder(
              borderRadius: BorderRadius.circular(12),
            ),
            padding: const EdgeInsets.symmetric(
              horizontal: 24,
              vertical: 12,
            ),
          ),
          child: Text(isEditing ? 'Mettre à jour' : 'Créer'),
        ),
      ],
    );
  }

  String _getStatusLabel(WaveStatus status) {
    switch (status) {
      case WaveStatus.active:
        return 'Active';
      case WaveStatus.closed:
        return 'Clôturée';
      case WaveStatus.draft:
        return 'Brouillon';
    }
  }
}
